ALTER TABLE businesses
    ADD COLUMN google_maps_url VARCHAR(1000),
    ADD COLUMN call_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN whatsapp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN maps_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN gallery_enabled BOOLEAN NOT NULL DEFAULT FALSE;