spring:
  application:
    name: ScanAura

  datasource:
    url: jdbc:postgresql://localhost:5432/scanaura
    username: postgres
    password: 705622

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true


  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 8080


jwt:
    secret: 1234567890123456789012345678901234567890123456789012345678901234
    expiration: 86400000

cloudinary:
  cloud-name: jkkm2fpw
  api-key: "161837288711125"
  api-secret: kZCpwn8LVoPA76hcKN9UExMyt98