name: Deploy Backend to EC2

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy backend
        shell: bash
        run: |
          set -e

          echo "======================================"
          echo "Starting ScanAura backend deployment"
          echo "======================================"

          cd /opt/scanaura/backend/backend

          echo "Pulling latest code..."
          git fetch origin master
          git reset --hard origin/master

          echo "Making Maven wrapper executable..."
          chmod +x mvnw

          echo "Building Spring Boot application..."
          MAVEN_OPTS="-Xmx512m -XX:MaxMetaspaceSize=256m" ./mvnw clean package -DskipTests

          echo "Checking generated JAR..."
          test -f target/scanaura-0.0.1-SNAPSHOT.jar

          echo "Restarting ScanAura backend..."
          sudo systemctl restart scanaura
          echo "Checking ScanAura service..."
          sudo systemctl is-active --quiet scanaura
          
          echo "Checking port 8080..."
          if ! sudo ss -ltnp | grep -q ':8080'; then
          echo "ERROR: Nothing is listening on port 8080."
          exit 1
          fi

          echo "Waiting for Spring Boot..."
          for i in {1..30}; do
          if curl --fail --silent --show-error \
          http://localhost:8080 > /dev/null; then
          echo "Spring Boot is responding."
          break
          fi
          if [ "$i" -eq 30 ]; then
          echo "ERROR: Spring Boot did not become ready within 60 seconds."
          exit 1
          fi
          echo "Waiting for Spring Boot... attempt $i/30"
          sleep 2
          done

          echo "======================================"
          echo "ScanAura backend deployment successful"
          echo "======================================"